data_and_analytics_dbt_bha:
  target: dev  
  outputs:
    dev:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DM_CO_CARE_COORD_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: SYSADMIN
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH
    qa:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DM_CO_CARE_COORD_QA
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: SYSADMIN
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH
    prod:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DM_CO_CARE_COORD_PROD
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: SYSADMIN
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH      
    test-location:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DM_BHA_LOCATION_REDESIGN_1
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH      
    test:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DM_CO_CARE_COORD_TEST
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH      
    dev-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DATALAKE_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: SYSADMIN
      schema: CO_CARE_COORDINATION_COMMCARE_DEV
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH
    qa-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DATALAKE_QA
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: SYSADMIN
      schema: CO_CARE_COORDINATION_COMMCARE_UAT
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH   
    prod-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DATALAKE_PROD
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: SYSADMIN
      schema: CO_CARE_COORDINATION_COMMCARE_PROD
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH
    test-location-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DATALAKE_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: BHA_LOCATION_REDESIGN_1
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH  
    test-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DATALAKE_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: CO_CARE_COORDINATION_COMMCARE_TEST
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH               

