data_and_analytics_dbt_bha:
  target: dev  
  outputs:
    dev:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DM_CO_CARE_COORD_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa      
    qa:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DM_CO_CARE_COORD_QA
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa         
    prod:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DM_CO_CARE_COORD_PROD
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH   
      authenticator: username_password_mfa            
    test-location:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DM_BHA_LOCATION_REDESIGN_1
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH  
      authenticator: username_password_mfa         
    test-perf:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DM_CO_CARE_COORD_PERF
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH  
      authenticator: username_password_mfa         
    test-train:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DM_CO_CARE_COORD_TRAIN
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH      
      authenticator: username_password_mfa                      
    test:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DM_CO_CARE_COORD_TEST
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH   
      authenticator: username_password_mfa         
    test-staging:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DM_CO_CARE_COORD_TEST_STAGING
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH   
      authenticator: username_password_mfa                 
    dev-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DATALAKE_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      schema: CO_CARE_COORDINATION_COMMCARE_DEV
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa         
    qa-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DATALAKE_QA
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      schema: CO_CARE_COORDINATION_COMMCARE_UAT
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH   
      authenticator: username_password_mfa         
    prod-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DATALAKE_PROD
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      schema: CO_CARE_COORDINATION_COMMCARE_PROD
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa    
    test-location-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DATALAKE_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: BHA_LOCATION_REDESIGN_1
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH  
      authenticator: username_password_mfa         
    test-perf-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DATALAKE_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: CO_CARE_COORDINATION_COMMCARE_PERF
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH  
      authenticator: username_password_mfa      
    test-train-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DATALAKE_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: CO_CARE_COORDINATION_COMMCARE_TRAIN
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH    
      authenticator: username_password_mfa                   
    test-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DATALAKE_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: CO_CARE_COORDINATION_COMMCARE_TEST
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH   
      authenticator: username_password_mfa         
    test-staging-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: DATALAKE_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: CO_CARE_COORDINATION_COMMCARE_TEST_STAGING
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH   
      authenticator: username_password_mfa         
    ## staging below
    sfstaging-dev:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT_STAGING') }}"
      database: DM_CO_CARE_COORD_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa         
    sfstaging-dev-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT_STAGING') }}"
      database: DATALAKE_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: CO_CARE_COORDINATION_COMMCARE_DEV
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH      
      authenticator: username_password_mfa         
    sfstaging-qa:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT_STAGING') }}"
      database: DM_CO_CARE_COORD_QA
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa         
    sfstaging-qa-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT_STAGING') }}"
      database: DATALAKE_QA
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: CO_CARE_COORDINATION_COMMCARE_UAT
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa         
    sfstaging-prod:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT_STAGING') }}"
      database: DM_CO_CARE_COORD_PROD
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa         
    sfstaging-prod-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT_STAGING') }}"
      database: DATALAKE_PROD
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: CO_CARE_COORDINATION_COMMCARE_PROD
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa         
    sfstaging-test-perf:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT_STAGING') }}"
      database: DM_CO_CARE_COORD_PERF
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa         
    sfstaging-test-perf-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT_STAGING') }}"
      database: DATALAKE_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: CO_CARE_COORDINATION_COMMCARE_PERF
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH           
      authenticator: username_password_mfa         
    sfstaging-test:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT_STAGING') }}"
      database: DM_CO_CARE_COORD_TEST
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa         
    sfstaging-test-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT_STAGING') }}"
      database: DATALAKE_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: CO_CARE_COORDINATION_COMMCARE_TEST
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa         
    sfstaging-test-staging:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT_STAGING') }}"
      database: DM_CO_CARE_COORD_TEST_STAGING
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa         
    sfstaging-test-staging-dl:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT_STAGING') }}"
      database: DATALAKE_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: CO_CARE_COORDINATION_COMMCARE_TEST_STAGING
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH 
      authenticator: username_password_mfa         