name: schedule_dbt_job_bha_qa_dm_dm_only
run-name: manual trigger from GitHub Actions to Snowflake
on: workflow_dispatch
env:
  DBT_PROFILES_DIR: ./
  DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
  DBT_SNOWFLAKE_USER_BHA: ${{ secrets.DBT_SNOWFLAKE_USER_BHA }}
  DBT_SNOWFLAKE_PWD_BHA: ${{ secrets.DBT_SNOWFLAKE_PWD_BHA }}
  DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}   
jobs:
  schedule_dbt_job_bha_qa_dm_dm_only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10.14'
      - name: Install dependencies
        run: |
          pip install dbt-snowflake
          dbt deps    
      - name: Run dbt models
        run: dbt run --models "DM_DB.DM.*" --target qa